remote_theme: "owasp/www--site-theme@main"

encoding: utf-8

# override default star and watch buttons
code_user: esapi-java-legacy
code_repo: esapi-java-legacy

# core files/folders to exclude
exclude:
 - README.md

plugins:
 - jekyll-include-cache-0.2.0
